services:
  payment-api:
    build: .
    container_name: payment-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=Payment;Username=postgres;Password=Mahtab;
