name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    name: Build & Test .NET
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Payment/payment.sln

      - name: Build
        run: dotnet build Payment/payment.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Payment/payment.sln --no-build --verbosity normal

  docker:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/payment-api:latest ./Payment

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/payment-api:latest
